theme = "catppuccin_frappe"

[editor]
true-color = true
end-of-line-diagnostics = "hint"
line-number = "relative"

[editor.statusline]
left = ["file-name", "total-line-numbers", "file-modification-indicator", "diagnostics"]
right = ["workspace-diagnostics", "spinner", "register", "version-control"]

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "hint"

[keys.normal.space]
o = ":sh zellij run -n Yazi -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/yazi-picker.sh open %{buffer_name}"
