[[language]]
name = "typescript"
language-servers = [ "typescript-language-server" ]
roots = ["package.json"]

[language.debugger]
name = "vscode-js-debug"
command = "bun"
args = ["/Users/mi/Developer/js-debug/src/dapDebugServer.js"]
transport = "tcp"
port-arg = "{} 127.0.0.1"

[[language.debugger.templates]]
name = "Launch"
request = "launch"
[[language.debugger.templates.completion]]
completion="filename"
name = "main"

[language.debugger.templates.args]
address = "127.0.0.1"
program = "{0}"
type = "pwa-node"

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.elixir-ls]
command = "elixir-ls"
config = { elixirLS.dialyzerEnabled = true }

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "svelte"
language-servers = [ "svelteserver", "tailwindcss-ls" ]


# [[language]]
# name = "elixir"
# language-id = "phoenix-heex"
# auto-format = true

[[language]]
name = "heex"
language-id = "phoenix-heex"
language-servers = [ "elixir-ls", "tailwindcss-ls", "vscode-html-language-server" ]
auto-format = true

[language-server.kotlin-lsp]
command = "/Users/mi/Downloads/kotlin-0/kotlin-lsp.sh"
args = ["--stdio"]

[[language]]
name = "kotlin"
language-servers = ["kotlin-lsp"]
